name: C++ Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install C++ 23
        run: sudo apt install -y g++-11
      - name: Check for C++ files
        run: |
          if [ -z "$(find . -name "*.cpp")" ]; then
            echo "No C++ files found"
            exit 0
          fi
      - name: Compile C++ code
        if: ${{ ! -z "$(find . -name "*.cpp")" }}
        run: g++-11 -std=c++23 -Wall -Wextra -Werror -pedantic *.cpp -o main
      - name: Run tests
        run: ./main
      - name: Upload build artifact
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: main
