name: C++ Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install C++ 23
        run: sudo apt install -y g++-11
      - name: Compile C++ code
        run: g++-11 -std=c++23 -Wall -Wextra -Werror -pedantic *.cpp -o main
      - name: Run tests
        run: ./main
      - name: Upload build artifact
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: main
